### ISSUE TITLE
Allow to use lulpeg instead of lpeg

### ISSUE THREAD

**Issue by Totktonada** [tarantool/graphql#3]
Don't sure whether it should be runtime autoguessing (pcall(require, 'lpeg'), then pcall(require, 'lulpeg')) or a user provided option.

lpeg did not work (crashes) on my system. This, however, was a long time ago.

**Comment by RunsFor** [comment]
We switched to `lulpeg` in #4 which is pure lua, so it should be more stable. One might say she want to use `lpeg` instead of `lulpeg`. I see only one major argument for this. It's performance. While it is an absolutely correct wish, it would be tedious to eliminate those "crashes" to make it work stable.

So lets proceed with `lulpeg` now, and come back to the question "`lpeg` or `lulpeg`" later.

BTW, there is also interesting project worth to look at called [lpeglabel](https://github.com/sqmedeiros/lpeglabel).
